/* Public research cards for Section 01. Source periods stay separate from Compass indices. */
(() => {
const categories=[
  {id:'shampoo',name:'洗发水',lead:'2025 年抖音洗发水公开规模与品牌格局见下方原始表格；2026 年不同平台和时间窗的数据单列。',annual:'108.99 亿元',annualNote:'2025 自然年 · 抖音洗发水销售额，观研天下网页公开表。',current:'173.14 亿元',currentNote:'2026 年 1—8 月 · 淘天＋京东＋抖音洗发水，混合销售口径。',share:'海飞丝 4.27%',shareNote:'2025 年抖音洗发水公开品牌榜榜首份额。',history:'下方保留 2025 年抖音洗发水市场规模和品牌 TOP 20；公开榜单并非成人洗发水专项。',scope:'2025 抖音单平台与 2026 多平台、洗发护发大类数据范围不同，不能直接计算同比或相加。',evidence:'2026 年参考表分别标明洗发水、洗发护发及洗发护发美发范围；宽口径数据不当作洗发水单类规模。'},
  {id:'soap',name:'洗发皂',lead:'2026 年上半年抖音洗发皂增长很快；头部品牌集中度可在同一平台和时间窗内计算。',annual:'暂无全年值',annualNote:'公开同比对应的 2025 上半年约 1.32 亿元为反推值，不是 2025 全年。',current:'6.69 亿元',currentNote:'2026.01—06 抖音 GMV，较 2025 同期 +406.19%；青眼情报初步数据、未经审计。',share:'前二约 47.7%',shareNote:'墨见 1.62 亿＋故事树 1.57 亿，除以抖音同期 6.69 亿；本稿计算。',history:'由 6.69 ÷ (1＋406.19%) 可得 2025 年上半年约 1.32 亿元，仅作为同比核算基数。没有依据推算 2025 全年。',scope:'仅抖音单平台 GMV。CR2 使用同一来源、同一平台、同一期间的品牌额和类目总额；因原文四舍五入，结果为约数。',bars:[['墨见',24.2],['故事树',23.5],['其他品牌',52.3]],evidence:'墨见和故事树合计 3.19 亿元，约占品类 47.7%；份额分别约 24.2% 和 23.5%。',sources:[['青眼情报 QYQB·2026 上半年洗发皂','https://caifuhao.eastmoney.com/news/20260731133936470736940']]},
  {id:'scalp',name:'头皮护理',lead:'“头皮护理”公开信息多是品牌榜或相邻的头皮精华赛道，不能直接充当全类目规模。',annual:'暂无全年值',annualNote:'没有找到可核对的 2025 自然年「头皮护理」独立销售额与同比。',current:'月榜品牌额',currentNote:'2026.06 抖音头皮护理榜：KOSHINE 1857 万元、三个魔发匠 1642 万元。',share:'暂无类目份额',shareNote:'公开月榜未给出整个头皮护理类目 GMV 分母。',history:'魔镜洞察称 2025 年 1—9 月“头皮精华/头皮养护”销售额 7.16 亿元、同比 +28.02%。其文注明分析由 AI 生成；这是相关子赛道和前三季度，不是全部头皮护理的 2025 全年数据。',scope:'“头皮精华/头皮养护”与平台叶子类目“头皮护理”可能交叉，但不是同义词；不能跨来源算份额或同比。',evidence:'2026.06 榜单销售额为品牌销售额，未披露该月类目总额和 2026 上半年合计。',sources:[['星图数据·2026 年 6 月抖音头皮护理榜','https://www.sohu.com/a/1050433300_121124358'],['魔镜洞察·2025 年 1—9 月头皮精华观察','https://column.iresearch.cn/b/202512/1017688.shtml']]},
  {id:'conditioner_mask',name:'护发素发膜',lead:'公开的 2026 年抖音榜单把护发素与发膜作为合并类目；分别计算市场规模会重复。',annual:'暂无合并全年值',annualNote:'没有可复核的 2025 自然年合并类目总额和同比。',current:'2026.08 合并榜',currentNote:'抖音品牌榜：理小养 3609 万元、固然堂 3371 万元，均为品牌销售额。',share:'暂无类目份额',shareNote:'公开品牌榜未给出护发素/发膜合并类目总额。',history:'2025 年护发素前三季度资料不含完整自然年，也不能代表护发素/发膜合并类目；未纳入主指标。',scope:'2026 年 8 月榜单按“护发素/发膜”合并统计；品牌销售额不是市场总额，不能据此计算市占率。',evidence:'理小养与固然堂金额只反映该月品牌在合并榜单的位置，不代表两个独立细分类目的规模。'},
  {id:'oil',name:'护发精油',lead:'三平台护发精油仍在扩容，但目前可直接核实的是滚动年度，不是 2025 自然年。',annual:'暂无可靠全年值',annualNote:'未找到同时写明 2025.01—12、分类范围和平台的可复核公开统计。',current:'31.32 亿元',currentNote:'截至 2026.06 的 MAT（2025.07—2026.06）·天猫＋抖音＋京东；同比 +18.2%。',share:'卡诗 27.1%',shareNote:'同一 MAT 三平台品类销售额份额；CR3 44.6%。',history:'2025 自然年：暂无可信的独立规模与同比；不可把截至 2026.06 的 MAT 当成 2025 年。',scope:'2026 数据是滚动 12 个月，含 2025 下半年；天猫、抖音、京东三平台之和也不是全渠道。',bars:[['天猫',53.2],['抖音',31.6],['京东',15.2]],evidence:'该 MAT 三平台分别为天猫 16.68 亿元、抖音 9.89 亿元、京东 4.76 亿元；卡诗 8.49 亿元。渠道份额和品牌份额来自同一报告，分别用不同分母计算。',sources:[['用户说·护发精油品类周参（2026.07.24）','https://www.sohu.com/a/1054347314_120045995']]},
];
const filters = document.getElementById('public-category-filters');
const view = document.getElementById('public-category-view');
const shampooResearch = document.getElementById('public-shampoo-research');
if (!filters || !view || !shampooResearch) return;
function render(id) {
  const c = categories.find(item => item.id === id) || categories[0];
  filters.innerHTML = categories.map(item => `<button type="button" data-id="${item.id}" aria-pressed="${item.id === c.id}">${item.name}</button>`).join('');
  shampooResearch.hidden = c.id !== 'shampoo';
  const bars = c.bars ? `<div class="public-category-bars">${c.bars.map(([label, value]) => `<div class="public-category-bar"><span>${label}</span><div class="public-category-track"><i style="width:${value}%"></i></div><strong>${value}%</strong></div>`).join('')}</div>` : '';
  view.innerHTML = `<div class="public-category-metrics"><article class="public-category-metric${c.annual.startsWith('暂无') ? ' missing' : ''}"><span>2025 全年 · ${c.name}</span><strong>${c.annual}</strong><small>${c.annualNote}</small></article><article class="public-category-metric"><span>2026 可核实窗口</span><strong>${c.current}</strong><small>${c.currentNote}</small></article><article class="public-category-metric"><span>市场 / 品牌份额</span><strong>${c.share}</strong><small>${c.shareNote}</small></article></div><article class="panel public-category-detail"><span class="eyebrow">${c.name} / 研究摘要</span><h3>${c.lead}</h3><div class="public-category-scope"><strong>口径提醒：</strong>${c.scope}</div><dl><dt>2025 年历史</dt><dd>${c.history}</dd><dt>2026 年信号</dt><dd>${c.evidence}${bars}</dd></dl></article>`;
  filters.querySelectorAll('button').forEach(button => button.addEventListener('click', () => render(button.dataset.id)));
}
render('shampoo');
})();
